#!/usr/bin/env bash
source /etc/birdnet/birdnet.conf
my_dir=$HOME/BirdNET-Pi/scripts
set -x
echo "============================================================================"
echo "CADDY CONFIGURATION UPDATE FOR BIRDNET-Pi"
echo "============================================================================"
echo ""
echo "The update script is NOT modifying your existing Caddyfile."
echo "Your BirdNET-Pi configuration has been saved to:"
echo "  $HOME/BirdNET-Pi/templates/Caddyfile.birdnet.example"
echo ""
echo "Please manually update your /etc/caddy/Caddyfile if needed."
echo ""

[ -d /etc/caddy ] || mkdir /etc/caddy
if ! [ -z ${CADDY_PWD} ];then
HASHWORD=$(caddy hash-password --plaintext ${CADDY_PWD})
cat << EOF > $HOME/BirdNET-Pi/templates/Caddyfile.birdnet.example
# BirdNET-Pi Caddy Configuration (Generated by update_caddyfile.sh)
# Manually add or update this in your /etc/caddy/Caddyfile

http:// ${BIRDNETPI_URL} {
  root * ${EXTRACTED}
  file_server browse
  handle /By_Date/* {
    file_server browse
  }
  handle /Charts/* {
    file_server browse
  }
  basicauth /views.php?view=File* {
    birdnet ${HASHWORD}
  }
  basicauth /Processed* {
    birdnet ${HASHWORD}
  }
  basicauth /scripts* {
    birdnet ${HASHWORD}
  }
  basicauth /stream {
    birdnet ${HASHWORD}
  }
  basicauth /phpsysinfo* {
    birdnet ${HASHWORD}
  }
  basicauth /terminal* {
    birdnet ${HASHWORD}
  }
  reverse_proxy /stream localhost:8000
  php_fastcgi unix//run/php/php-fpm.sock
  reverse_proxy /log* localhost:8080
  reverse_proxy /stats* localhost:8501
  reverse_proxy /terminal* localhost:8888
}
EOF
else
  cat << EOF > $HOME/BirdNET-Pi/templates/Caddyfile.birdnet.example
# BirdNET-Pi Caddy Configuration (Generated by update_caddyfile.sh)
# Manually add or update this in your /etc/caddy/Caddyfile

http:// ${BIRDNETPI_URL} {
  root * ${EXTRACTED}
  file_server browse
  handle /By_Date/* {
    file_server browse
  }
  handle /Charts/* {
    file_server browse
  }
  reverse_proxy /stream localhost:8000
  php_fastcgi unix//run/php/php-fpm.sock
  reverse_proxy /log* localhost:8080
  reverse_proxy /stats* localhost:8501
  reverse_proxy /terminal* localhost:8888
}
EOF
fi

cat $HOME/BirdNET-Pi/templates/Caddyfile.birdnet.example

echo ""
echo "============================================================================"
echo "Configuration saved. To apply changes:"
echo "  1. Edit /etc/caddy/Caddyfile with your preferred setup"
echo "  2. Run: sudo systemctl reload caddy"
echo "============================================================================"
